### ISSUE TITLE
Checkpointer support not present in code

### ISSUE THREAD

**Issue by davireis** [usedatabrew/pglogicalstream#3] opened 2024-04-29 12:57 UTC
The README.md mentions the checkpointer support, which is a fantastic feature. But it does not seem to exist in code?

https://github.com/search?q=repo%3Ausedatabrew%2Fpglogicalstream%20CheckPointer&type=code

**Comment by le-vlad** [comment] 2024-04-30 13:05
Hello, @davireis.
Regarding the checkpointer. We had checkpointer support earlier. But at this moment it was removed.

Since WAL is being consumed in "chunks" there is no real need to have such functionality. After restarting you will receive updates from the last confirmed WAL position.

But feel free to share your use case for checkpointer. I may add it back if it's needed.

**Comment by le-vlad** [comment] 2024-05-17 10:24
Since there is no reply. I'll be closing this issue.
@davireis Feel free to reach out to me in case you need more help

**Closed as completed by le-vlad** 2024-05-17 10:24 UTC
Labels: help wanted
